css
style
^ '
body{
	background-color: black;
	}
	
#header{
color: white;
font-family: monospace;
border:0px;
height: 70px;
margin-left: 5px;
margin-right: 5px;
padding-left: 5px;
padding-right: 5px;
padding-top: 5px;
padding-bottom: 5px;
background-color: black;
}

#content{
color: white;
font-family: monospace;
text-align: justify;
margin-left: 5px;
margin-right: 5px;
padding-left: 5px;
padding-right: 5px;
padding-top: 5px;
padding-bottom: 5px;
background-color: black;
border:0px;
}

#tabs{
list-style-type: none;
margin-top: 2px;
margin-bottom: 10px;
}

#tabs li{
display:inline;
}

#tabs li a{
font-family: monospace;
text-align: center;
width: 100%;
height: 25px;
color: #ff9800;
background-color: black;
margin: 0.5em;
padding: 0.5em;
font-size: 14px;
text-decoration: none;
border-color: white;
}

#tabs li a:hover{
	font-weight: bold;
	background-color:#ff2e88;
	color:#fff
}

#content a{
	text-decoration: none;
	border-bottom-width: 1px;
	border-bottom-style: solid;
	border-bottom-color: #ff2e88;
}

#content a:link{
	color: #ff9800;
}

#content a:visited {
    color: #ff9800;
}

#content a:hover{
    background-color:#ff2e88;
    color:#fff} 
'
